language: go
go:
  - 1.11.x
script:
  - GO111MODULE=on GOOS=windows go install -mod vendor github.com/liujianping/job
  - GO111MODULE=on GOOS=linux go install -mod vendor github.com/liujianping/job
  - GO111MODULE=on GOOS=darwin go install -mod vendor github.com/liujianping/job